apiVersion: v1
kind: Secret
metadata:
  name: lokistack-minio
  namespace: openshift-logging
stringData:
  access_key_id: minioadmin
  access_key_secret: minioadmin
  bucketnames: loki-bucket
  endpoint: http://minio-minio.apps.ocp4.example.com
  region: minio
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  size: 1x.extra-small
  storageClassName: managed-nfs-storage
  storage:
    secret:
      name: lokistack-minio
      type: s3
  tenants:
    mode: openshift-logging    
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
  collection:
    type: vector
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines: 
  - name: all-to-default
    inputRefs:
    - infrastructure
    - application
    - audit
    outputRefs:
    - default
