apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: quay.io/openshift/origin-cli
            args:
            - /bin/sh
            - -c
            - oc get csr -oname | xargs oc adm certificate approve
          restartPolicy: OnFailure
