apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: openshift-operators
spec:
  channel: ${SUB_CHANNEL}
  installPlanApproval: "Manual"
  name: quay-operator
  source: $CATALOG_SOURCE
  sourceNamespace: openshift-marketplace
