apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: ${NAMESPACE}
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: objectstorage
      managed: false
