apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: ${NAMESPACE}
spec:
  configBundleSecret: ${BUCKET_NAME}-credentials
  components:
    - kind: objectstorage
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
