apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: ${NAMESPACE}
spec:
  configBundleSecret: quay-config
  components:
    - kind: objectstorage
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
    - kind: quay
      managed: true
      overrides:
        replicas: $REPLICAS
    - kind: clair
      managed: true
      overrides:
        replicas: $REPLICAS
    - kind: mirror
      managed: true
      overrides:
        replicas: $REPLICAS
