apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: ${NAMESPACE}
spec:
  configBundleSecret: ${BUCKET_NAME}-credentials
  components:
    - kind: objectstorage
      managed: false
    - kind: quay
      managed: true
    - kind: clair
      managed: true
      overrides:
        replicas: 2
    - kind: horizontalpodautoscaler
      managed: false
