apiVersion: v1
kind: Secret
metadata:
  name: ${BUCKET_NAME}-credentials
  namespace: openshift-logging
stringData:
  access_key_id: ${ACCESS_KEY_ID}
  access_key_secret: ${ACCESS_KEY_SECRET}
  bucketnames: ${BUCKET_NAME}
  endpoint: ${BUCKET_HOST}
  region: minio
