apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators 
spec:
  channel: ${SUB_CHANNEL}
  installPlanApproval: "Manual"
  name: openshift-pipelines-operator-rh
  source: ${CATALOG_SOURCE}
  sourceNamespace: openshift-marketplace
