apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators 
spec:
  channel: ${CHANNEL_NAME}
  installPlanApproval: "Manual"
  name: openshift-pipelines-operator-rh
  source: ${CATALOG_SOURCE_NAME}
  sourceNamespace: openshift-marketplace
