apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: es-im-app-job-cleanup-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: es-im-app-job-cleanup-binding
subjects:
- kind: ServiceAccount
  name: es-im-app-job-cleanup-sa
  namespace: es-im-app-job-cleanup
roleRef:
  kind: ClusterRole
  name: es-im-app-job-cleanup-role
  apiGroup: rbac.authorization.k8s.io
