apiVersion: batch/v1
kind: CronJob
metadata:
  name: es-im-app-job-cleanup
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup-job
            image: quay.io/openshift/origin-cli
            command: ["/bin/sh", "-c"]
            args:
            - |
              latest_job=$(oc -n openshift-logging get job -o custom-columns=:metadata.creationTimestamp,:metadata.name --sort-by=.metadata.creationTimestamp | grep elasticsearch-im-app | tail -n 1 | awk '{print $2}')
              job_status=$(oc -n openshift-logging get job $latest_job -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}')
              if [ "$job_status" == "True" ]; then
                failed_job_1=$(oc -n openshift-logging get job --field-selector=metadata.name!=$latest_job | grep "elasticsearch-im-app" | grep "0/1" | awk '{print $1}')

                if [ -n "$failed_job_1" ]; then
                  failed_job_2=$(oc -n openshift-logging get job $failed_job_1 -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}')

                  if [ "$failed_job_2" == "True" ]; then
                    oc -n openshift-logging delete job $failed_job_1
                  fi
                fi
              fi
          restartPolicy: "Never"
          serviceAccountName: "es-im-app-job-cleanup-sa"
          serviceAccount: es-im-app-job-cleanup-sa
