apiVersion: v1
kind: ConfigMap
metadata:
  name: jboos-configmap
data:
  index.jsp: |
    <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Log Test</title>
    </head>
    <body>
    <%
        out.print("Hello World");
        System.out.println("Hello World");
    %>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jboos
  template:
    metadata:
      labels:
        app: jboos
    spec:
      containers:
      - name: jboos-container
        image: registry.redhat.io/jboss-webserver-5/jws57-openjdk11-openshift-rhel8:5.7.3-2.1687186259
        ports:
        - containerPort: 8778
          protocol: TCP
        - containerPort: 9404
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: app-files
          mountPath: /deployments/ROOT
      volumes:
      - name: app-files
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jboos-service
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  - name: 9404-tcp
    port: 9404
    protocol: TCP
    targetPort: 9404
  selector:
    deployment: jboos
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jboos-route
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: jboos-service
    weight: 100
  wildcardPolicy: None
