apiVersion: v1
kind: ConfigMap
metadata:
  name: jboos-app-configmap
data:
  index.jsp: |
    <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Log Test</title>
    </head>
    <body>
    <%
        out.print("Hello World");
        System.out.println("Hello World");
    %>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jboos
  template:
    metadata:
      labels:
        app: jboos
    spec:
      containers:
      - name: jboos-container
        image: registry.redhat.io/jboss-webserver-5/jws57-openjdk11-openshift-rhel8:5.7.3-2.1687186259
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-files
          mountPath: /deployments/ROOT
      volumes:
      - name: app-files
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jboos-service
spec:
  selector:
    app: jboos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    deployment: jboos-app
  sessionAffinity: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jboos-route
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: jboos-service
    weight: 100
  wildcardPolicy: None
