apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }
  
    http {
        server {
            listen 8080;
            server_name localhost;

            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;

                auth_basic "Restricted Access";
                auth_basic_user_file /etc/nginx/.htpasswd;
            }
        }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-files
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Welcome to Nginx!</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
      <p>This HTML content is served by Nginx from a ConfigMap.</p>
    </body>
    </html>
