apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
 name: instance
 namespace: openshift-logging
spec:
 outputs: 
  - name: elasticsearch-insecure
    type: elasticsearch
    url: 'http://elasticsearch-server.${NAMESPACE}.svc:9200'
 pipelines:
  - name: forward-to-elasticsearch-insecure
    inputRefs:
    - infrastructure
    - application
    - audit
    outputRefs:
    - default
    - elasticsearch-insecure
