apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
 name: instance
 namespace: openshift-logging
spec:
 outputs: 
  - name: kafka-server-insecure
    url: tls://my-cluster-kafka-bootstrap.${NAMESPACE}.svc:9092/topic-logging-app
    type: kafka
 pipelines:
  - name: forward-to-kafka-insecure 
    inputRefs:
    - infrastructure
    - application
    - audit
    outputRefs:
    - default
    - kafka-server-insecure
