apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: val-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
    name: val-webhook.coffeewhale.com
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - webhooktest
    rules:
      - operations:
          - CREATE
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - "*"
    sideEffects: None
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVUWNuS3VUMHpnVnprem5QQi8zUkdPWlQ2ZFlrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSXpNRGd3TXpBeU16WXdNRm9ZRHpJeQpPVGN3TlRFNE1ESXpOakF3V2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURQTlZPd0h4cG4zQ2N6YUxxNUpaNHRnYlhIWEpDNmErVDcKdy9XUGFHZmFtNUpzMnZXZGNyRUNMTzBzbTVTKzEwYUNBRzBMRk82YTNQMlp2YmFFWkJvMU1CRUMvQXBlTlB5ZgpOcUJlcXREdURpeWd4NmRWcEYvWjh4L2szK21nSUNSWldhdDhPbjl0R1I1T2p5UDlkK0hLL1RKTWJhMmZoUWJsCjVray8yc21wYW1xMW1qVlZLWERZdUI1UHk4VWdLajQxZm1YREVvcEgrV1V5aThkRmwvckkxb1BJK0VYeUVUWVAKRTZocGlERG1ScktvZ2JSZFY4OTROOXJrMlY3TFljNGNIUTdRc25OdmR2Yk9XeVBXamEyTk1TWGh5elZpTkNRdQp1aFRsMWl1Nm0zNENTN0tRNm55cGxySGVCbXh5citUMXZ6cC96TFhJclc5ektXVE1xY3JKQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCU0xzSnhBWW82ZEZEMUV2OVFqYmJ6dzNjQVF0VEFmQmdOVkhTTUVHREFXZ0JTTHNKeEEKWW82ZEZEMUV2OVFqYmJ6dzNjQVF0VEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCaE5sUU1Ga3Q0NXVUVGJkVDJxT3NXdldBckRycTlUSC83TXFIQWZSOXNrR1ZVaVR6MUk3Qlh1YlJrCld0SFdpVi9Kbm1HWXBrODA2bmkzMlhpZTJ5ZDMvYU9ZMTBoYlg5T3k4akNIcWFhTXJRNDlUS3p4KytKQmFJWGEKNXpqbkQ0aDJoWmRuUWpYR2Y1Qkt5NUR3M1dzMGtseDRjbENiNHpYaVk1RlRDL0ZjMnVFUllUUHdMbWNPakxDNQp4U0hYakhlRE84VGQySzBWOXNlUWI2aUNEZHlNYW50dUNveEtXRUx2QTBsSXhQeGc2SDRhZm1uemZFNWVabUJrClVhclJ0dm13Qjl6UHNreUkvTEkxRVRjMk1ORW5OWm9EQWZ2SU9VZTk1VEY4L3Q3V1U1eHpwZkFkMXA5Y2doNHIKUGpLWmdGVS8vZWxlYXBSRi9RVGVxampuVzA5bQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: webhooktest
        name: webhook
        port: 443
