apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: ${CHANNEL_NAME}
  installPlanApproval: "Manual"
  name: openshift-gitops-operator 
  source: ${CATALOG_SOURCE_NAME}
  sourceNamespace: openshift-marketplace 
