apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: gitops-client
  namespace: ${NAMESPACE}
  labels:
    app: sso
spec:
  client:
    clientId: gitops-demo
    clientAuthenticatorType: client-secret
    publicClient: false
    protocol: openid-connect
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    redirectUris:
      - https://$GITOPS_HOST/*
    defaultClientScopes:
      - acr
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  realmSelector:
     matchLabels:
      app: sso
  scopeMappings: {}
