apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    openshift.io/cluster-monitoring: "true" 
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhsso-operator-group
spec:
  targetNamespaces:
  -  ${NAMESPACE} # change this to the namespace you will use for RH-SSO
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
spec:
  channel: ${CHANNEL}
  installPlanApproval: Manual
  name: rhsso-operator
  source: ${CATALOG_SOURCE_NAME}
  sourceNamespace: openshift-marketplace
