apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    app: keycloak
spec:
  capacity:
    storage: 1Gi
  accessModes:      
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: ${NFS_PATH}
    server: ${NFS_IP}
