apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: example-client
  namespace: ${NAMESPACE}
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  client:
    clientId: openshift-demo
    secret: client-secret
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    redirectUris:
      - https://${OAUTH_HOST}/*
      - https://${CONSOLE_HOST}/*
    defaultClientScopes:
      - acr
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
