apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: ${USER_NAME}
  namespace: ${NAMESPACE}
spec:
  user:
    username: ${USER_NAME}
    credentials:
      - type: "password"
        value: "${PASSWORD}"
    enabled: true
    realmRoles:
      - "default-roles-openshift"
  realmSelector:
    matchLabels:
      app: sso
