#!/bin/bash

oc adm -a ${LOCAL_SECRET_JSON} release mirror \
  --from=quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE} \
  --to=${LREGISTRY_HOSTNAM}:5000/${LOCAL_REPOSITORY} \
  --to-release-image=${LREGISTRY_HOSTNAM}:5000/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE} 
